#! /bin/sh

# This script should be run in a virtual environment that contains this
# distribution.

# This will also require access to a redis machine that is defined in 
# the config.ini file.

celery -A tldist.celery worker --loglevel=info -c 4
